# Generated by Django 3.2.9 on 2021-12-06 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('person', models.IntegerField(default=1)),
                ('table', models.CharField(blank=True, choices=[('Inside', 'Inside'), ('Outside', 'Outside'), ('Upstair', 'Upstair'), ('Downstair', 'Downstair'), ('Window', 'Window')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
