# Generated by Django 3.2.9 on 2021-12-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.TimeField(),
        ),
    ]
